name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via Ansible
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      ANSIBLE_FORCE_COLOR: 1
      ANSIBLE_HOST_KEY_CHECKING: no
    steps:
      - name: Checkout the code
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/kawajevo
          echo "$SSH_KEY" > ~/.ssh/kawajevo/root_rsa
          chmod 600 ~/.ssh/kawajevo/root_rsa
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$DEPLOY_KEY" > ~/.ssh/kawajevo/deploy_rsa
          chmod 600 ~/.ssh/kawajevo/deploy_rsa
          cat >>~/.ssh/config <<END
          Host "io37.ch"
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/kawajevo/root_rsa
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: root
          SSH_KEY:  ${{ secrets.ROOT_RSA }}
          DEPLOY_KEY:  ${{ secrets.DEPLOY_RSA }}
          SSH_HOST: io37.ch

      - name: Configure SSH ii
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/kawajevo/deploy_rsa
          chmod 600 ~/.ssh/kawajevo/deploy_rsa
        env:
          SSH_KEY:  ${{ secrets.DEPLOY_RSA }}
 
      - name: Download Ansible roles
        run: ansible-galaxy install -r .deploy/requirements.yml

      - name: Deploy the code
        env:
          MASTER_KEY:  ${{ secrets.MASTER_KEY }}
          DB_PASSWORD:  ${{ secrets.MASTER_KEY }}
          KEY_PATH: ~/.ssh/kawajevo/deploy_rsa
        run: >
          ansible-playbook -i .deploy/hosts.ini .deploy/deploy.yml -e "master_key=$MASTER_KEY db_password=$MASTER_KEY ansistrano_deploy_branch=$GITHUB_SHA ansistrano_git_identity_key_path=$KEY_PATH" -vv
